/**
 * Convert markdown text to a PDF buffer.
 *
 * Uses `jspdf` for server-side PDF generation.
 * Handles: headings, paragraphs, bullet lists, numbered lists, bold text.
 * Adds header/footer branding and page numbers.
 */

import { jsPDF } from 'jspdf';

interface PdfOptions {
  title: string;
  /** Footer branding text. Default: "Generated by GovSecure" */
  branding?: string;
}

/**
 * Convert markdown string to a PDF buffer.
 */
export async function markdownToPdf(markdown: string, options: PdfOptions): Promise<Buffer> {
  const { title, branding = 'Generated by GovSecure' } = options;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 20;
  const marginRight = 20;
  const marginTop = 25;
  const marginBottom = 25;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let y = marginTop;
  let pageNum = 1;

  const addFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(branding, marginLeft, pageHeight - 12);
    doc.text(`Page ${pageNum}`, pageWidth - marginRight, pageHeight - 12, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  };

  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - marginBottom) {
      addFooter();
      doc.addPage();
      pageNum++;
      y = marginTop;
    }
  };

  // ── Title page header ──
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(title, pageWidth / 2, y + 10, { align: 'center' });
  y += 18;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(120, 120, 120);
  doc.text(`${branding} · ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  y += 10;

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 8;

  // ── Parse and render markdown lines ──
  const lines = markdown.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed) {
      y += 3;
      continue;
    }

    // Headings
    if (trimmed.startsWith('#### ')) {
      checkPageBreak(8);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      const text = trimmed.slice(5);
      doc.text(text, marginLeft, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      continue;
    }
    if (trimmed.startsWith('### ')) {
      checkPageBreak(10);
      y += 2;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      const text = trimmed.slice(4);
      doc.text(text, marginLeft, y);
      y += 7;
      doc.setFont('helvetica', 'normal');
      continue;
    }
    if (trimmed.startsWith('## ')) {
      checkPageBreak(12);
      y += 4;
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      const text = trimmed.slice(3);
      doc.text(text, marginLeft, y);
      y += 8;
      doc.setFont('helvetica', 'normal');
      continue;
    }
    if (trimmed.startsWith('# ')) {
      checkPageBreak(14);
      y += 5;
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      const text = trimmed.slice(2);
      doc.text(text, marginLeft, y);
      y += 9;
      doc.setFont('helvetica', 'normal');
      continue;
    }

    // Bullet list
    if (/^[-*] /.test(trimmed)) {
      const text = trimmed.slice(2);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const wrappedLines = doc.splitTextToSize(text, contentWidth - 8);
      checkPageBreak(wrappedLines.length * 5 + 2);
      doc.text('•', marginLeft + 2, y);
      doc.text(wrappedLines, marginLeft + 8, y);
      y += wrappedLines.length * 5 + 1;
      continue;
    }

    // Numbered list
    const numMatch = trimmed.match(/^(\d+)\.\s+(.+)/);
    if (numMatch) {
      const num = numMatch[1];
      const text = numMatch[2];
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const wrappedLines = doc.splitTextToSize(text, contentWidth - 10);
      checkPageBreak(wrappedLines.length * 5 + 2);
      doc.setFont('helvetica', 'bold');
      doc.text(`${num}.`, marginLeft + 2, y);
      doc.setFont('helvetica', 'normal');
      doc.text(wrappedLines, marginLeft + 10, y);
      y += wrappedLines.length * 5 + 1;
      continue;
    }

    // Regular paragraph — strip markdown bold markers for rendering
    const plainText = trimmed.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const wrappedLines = doc.splitTextToSize(plainText, contentWidth);
    checkPageBreak(wrappedLines.length * 5 + 2);
    doc.text(wrappedLines, marginLeft, y);
    y += wrappedLines.length * 5 + 2;
  }

  // Add footer to the last page
  addFooter();

  // Convert to Buffer
  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}