/**
 * Convert markdown text to a DOCX buffer.
 *
 * Handles: headings (H1-H4), paragraphs, bullet lists, numbered lists, bold, italic.
 * Uses the `docx` npm package for server-side generation.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Footer,
  PageNumber,
  NumberFormat,
} from 'docx';

interface ParsedLine {
  type: 'h1' | 'h2' | 'h3' | 'h4' | 'bullet' | 'numbered' | 'paragraph' | 'empty';
  text: string;
  number?: number;
}

/**
 * Parse markdown text into structured lines.
 */
function parseMarkdown(markdown: string): ParsedLine[] {
  const lines = markdown.split('\n');
  return lines.map((line) => {
    const trimmed = line.trim();

    if (!trimmed) return { type: 'empty', text: '' };
    if (trimmed.startsWith('#### ')) return { type: 'h4', text: trimmed.slice(5) };
    if (trimmed.startsWith('### ')) return { type: 'h3', text: trimmed.slice(4) };
    if (trimmed.startsWith('## ')) return { type: 'h2', text: trimmed.slice(3) };
    if (trimmed.startsWith('# ')) return { type: 'h1', text: trimmed.slice(2) };
    if (/^[-*] /.test(trimmed)) return { type: 'bullet', text: trimmed.slice(2) };

    const numMatch = trimmed.match(/^(\d+)\.\s+(.+)/);
    if (numMatch) return { type: 'numbered', text: numMatch[2], number: parseInt(numMatch[1]) };

    return { type: 'paragraph', text: trimmed };
  });
}

/**
 * Parse inline markdown formatting (bold, italic) into TextRun array.
 */
function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = [];
  // Match **bold**, *italic*, and plain text
  const regex = /(\*\*(.+?)\*\*)|(\*(.+?)\*)|([^*]+)/g;
  let match;

  while ((match = regex.exec(text)) !== null) {
    if (match[2]) {
      // Bold
      runs.push(new TextRun({ text: match[2], bold: true, font: 'Calibri', size: 22 }));
    } else if (match[4]) {
      // Italic
      runs.push(new TextRun({ text: match[4], italics: true, font: 'Calibri', size: 22 }));
    } else if (match[5]) {
      // Plain text
      runs.push(new TextRun({ text: match[5], font: 'Calibri', size: 22 }));
    }
  }

  return runs.length > 0 ? runs : [new TextRun({ text, font: 'Calibri', size: 22 })];
}

/**
 * Convert markdown to a DOCX buffer.
 */
export async function markdownToDocx(markdown: string, title: string): Promise<Buffer> {
  const parsed = parseMarkdown(markdown);
  const children: Paragraph[] = [];

  // Title page
  children.push(
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
  );
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by GovSecure · ${new Date().toLocaleDateString()}`,
          font: 'Calibri',
          size: 20,
          color: '888888',
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  );

  // Content
  for (const line of parsed) {
    switch (line.type) {
      case 'h1':
        children.push(new Paragraph({ text: line.text, heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 100 } }));
        break;
      case 'h2':
        children.push(new Paragraph({ text: line.text, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 80 } }));
        break;
      case 'h3':
        children.push(new Paragraph({ text: line.text, heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 60 } }));
        break;
      case 'h4':
        children.push(new Paragraph({ text: line.text, heading: HeadingLevel.HEADING_4, spacing: { before: 160, after: 40 } }));
        break;
      case 'bullet':
        children.push(new Paragraph({ children: parseInlineFormatting(line.text), bullet: { level: 0 }, spacing: { before: 40, after: 40 } }));
        break;
      case 'numbered':
        children.push(new Paragraph({
          children: [
            new TextRun({ text: `${line.number}. `, bold: true, font: 'Calibri', size: 22 }),
            ...parseInlineFormatting(line.text),
          ],
          spacing: { before: 40, after: 40 },
        }));
        break;
      case 'paragraph':
        children.push(new Paragraph({ children: parseInlineFormatting(line.text), spacing: { before: 60, after: 60 } }));
        break;
      case 'empty':
        children.push(new Paragraph({ text: '', spacing: { before: 60, after: 60 } }));
        break;
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        children,
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: 'GovSecure · Page ', font: 'Calibri', size: 18, color: '999999' }),
                  new TextRun({ children: [PageNumber.CURRENT], font: 'Calibri', size: 18, color: '999999' }),
                ],
              }),
            ],
          }),
        },
      },
    ],
    numbering: {
      config: [
        {
          reference: 'default-numbering',
          levels: [
            { level: 0, format: NumberFormat.DECIMAL, text: '%1.', alignment: AlignmentType.START },
          ],
        },
      ],
    },
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
