"use client";

import Link from "next/link";
import { lifecycleTemplates } from "@/data/content";
import { BookOpen, ArrowUpRight, Download } from "lucide-react";

// ─── Template content generators ─────────────────────────────────────────────

const today = () => new Date().toISOString().split("T")[0];

const templateContent: Record<string, () => string> = {
  "ai-inventory": () => `AI INVENTORY TEMPLATE
Generated by GovSecure · ${today()}
─────────────────────────────────────────────────────────────

PURPOSE
Maintain an audit-ready registry of every AI system, model, tool, and use
case deployed or under evaluation in your organization.

─────────────────────────────────────────────────────────────
INVENTORY REGISTER
─────────────────────────────────────────────────────────────

SYSTEM NAME:          ________________________________
SYSTEM ID:            ________________________________
DESCRIPTION:          ________________________________
BUSINESS OWNER:       ________________________________
TECHNICAL OWNER:      ________________________________
VENDOR / PROVIDER:    ________________________________
DATE DEPLOYED:        ________________________________

USE CASE CATEGORY (tick one):
  □ Customer-facing decision-making
  □ Internal process automation
  □ Content generation
  □ Predictive analytics
  □ Monitoring / surveillance
  □ Other: _____________________________

DATA PROCESSED:
  □ Personal data (GDPR applies)
  □ Sensitive / special-category data
  □ Non-personal / anonymised data
  Data types: ___________________________

RISK TIER (tick one):
  □ Low       — minimal harm potential, no sensitive data
  □ Medium    — moderate impact, limited personal data
  □ High      — significant decisions, sensitive data
  □ Critical  — high-stakes decisions, regulated context

LIFECYCLE STATUS (tick one):
  □ Evaluation    □ Approved    □ Live    □ Deprecated    □ Retired

REVIEW DATE:          ________________________________
NOTES:                ________________________________

─────────────────────────────────────────────────────────────
Add one row per system. Repeat the block above as needed.
─────────────────────────────────────────────────────────────
Generated free by GovSecure · govsecure.ai
`,

  "ai-use-case-form": () => `AI USE CASE INTAKE FORM
Generated by GovSecure · ${today()}
─────────────────────────────────────────────────────────────

PURPOSE
Capture, triage, and route proposed or materially changed AI use cases
before governance review and formal approval.

─────────────────────────────────────────────────────────────
SECTION 1 — SUBMITTER DETAILS
─────────────────────────────────────────────────────────────

Name:                 ________________________________
Role / Team:          ________________________________
Date Submitted:       ________________________________
Business Sponsor:     ________________________________

─────────────────────────────────────────────────────────────
SECTION 2 — USE CASE DESCRIPTION
─────────────────────────────────────────────────────────────

Use Case Name:        ________________________________
Objective:            ________________________________
                      ________________________________
AI System / Tool:     ________________________________
Vendor (if any):      ________________________________
Is this a change to an existing system?   □ Yes  □ No
If yes, describe change: ______________________________

─────────────────────────────────────────────────────────────
SECTION 3 — DATA & IMPACT
─────────────────────────────────────────────────────────────

Data involved (tick all that apply):
  □ Personal data          □ Sensitive / special-category
  □ Financial data         □ Health data
  □ Children's data        □ No personal data

Will AI outputs directly affect individuals?   □ Yes  □ No
Describe the impact:  ________________________________

Estimated number of people affected: ________________

─────────────────────────────────────────────────────────────
SECTION 4 — RISK INDICATORS (auto-High triggers)
─────────────────────────────────────────────────────────────

Tick any that apply — if any box is ticked, risk tier is High minimum:
  □ Automated decisions without human review
  □ Biometric or facial recognition data
  □ Children or vulnerable individuals in scope
  □ Law enforcement or public safety context
  □ Credit, insurance, or employment decisions
  □ Processing at large scale (>100,000 individuals)

─────────────────────────────────────────────────────────────
SECTION 5 — PRELIMINARY RISK TIER
─────────────────────────────────────────────────────────────

Submitter's assessment (tick one):
  □ Low    □ Medium    □ High    □ Critical

Governance reviewer's assessment:
  □ Low    □ Medium    □ High    □ Critical

Reviewer name:        ________________________________
Review date:          ________________________________

─────────────────────────────────────────────────────────────
Generated free by GovSecure · govsecure.ai
`,

  "risk-assessment": () => `AI RISK ASSESSMENT TEMPLATE
Generated by GovSecure · ${today()}
─────────────────────────────────────────────────────────────

PURPOSE
Assess each AI use case for potential harm, data sensitivity, and
compliance exposure before governance sign-off.

─────────────────────────────────────────────────────────────
SECTION 1 — USE CASE REFERENCE
─────────────────────────────────────────────────────────────

Use Case Name:        ________________________________
System / Tool:        ________________________________
Assessor:             ________________________________
Assessment Date:      ________________________________

─────────────────────────────────────────────────────────────
SECTION 2 — HARM ASSESSMENT
─────────────────────────────────────────────────────────────

Score each dimension 1 (low) → 4 (critical):

DIMENSION                          SCORE    NOTES
─────────────────────────────────────────────────────────────
Severity of potential harm         _____    ________________
Breadth (number of people)         _____    ________________
Reversibility of harm              _____    ________________
Vulnerability of affected groups   _____    ________________
Likelihood of harm occurring       _____    ________________
Presence of human oversight        _____    ________________

Total Score (sum): _____   (max 24)

Risk Band:
  6–9  → Low      10–14 → Medium
  15–19 → High    20–24 → Critical

─────────────────────────────────────────────────────────────
SECTION 3 — REGULATORY EXPOSURE
─────────────────────────────────────────────────────────────

Applicable regulations (tick all that apply):
  □ GDPR / UK GDPR          — personal data processing
  □ EU AI Act                — high-risk AI system
  □ NIST AI RMF              — voluntary framework reference
  □ ISO/IEC 42001            — AI management system
  □ Sector-specific rules    — specify: ________________

DPIA required?    □ Yes  □ No  □ TBC
EU AI Act tier:   □ Unacceptable  □ High  □ Limited  □ Minimal

─────────────────────────────────────────────────────────────
SECTION 4 — MITIGATION MEASURES
─────────────────────────────────────────────────────────────

RISK IDENTIFIED               MITIGATION                 OWNER       DUE DATE
─────────────────────────────────────────────────────────────────────────────
________________________      ___________________        _______     ________
________________________      ___________________        _______     ________
________________________      ___________________        _______     ________
________________________      ___________________        _______     ________

─────────────────────────────────────────────────────────────
SECTION 5 — SIGN-OFF
─────────────────────────────────────────────────────────────

Residual Risk Level:   □ Low   □ Medium   □ High   □ Critical

Assessor signature:   ________________________________
DPO / Legal review:   ________________________________
Approved by:          ________________________________
Date:                 ________________________________

─────────────────────────────────────────────────────────────
Generated free by GovSecure · govsecure.ai
`,

  "risk-tiering": () => `AI RISK TIERING FRAMEWORK
Generated by GovSecure · ${today()}
─────────────────────────────────────────────────────────────

PURPOSE
Classify AI use cases into risk tiers to calibrate the controls,
oversight, and approvals each one requires.

─────────────────────────────────────────────────────────────
TIER DEFINITIONS
─────────────────────────────────────────────────────────────

TIER 1 — LOW RISK
  Characteristics:
  • Minimal or no impact on individuals
  • No personal or sensitive data
  • Human reviews all AI outputs before action
  • Fully reversible outcomes
  Examples: internal search tools, draft content suggestion,
            data formatting, coding assistants for internal teams
  Controls required:
  □ Basic documentation
  □ Annual review

─────────────────────────────────────────────────────────────

TIER 2 — MEDIUM RISK
  Characteristics:
  • Moderate impact on individuals or operations
  • Limited personal data involved
  • Human oversight present but not mandatory for every output
  • Outcomes reversible with effort
  Examples: customer service chatbots, marketing personalisation,
            internal HR analytics, vendor shortlisting tools
  Controls required:
  □ Use case intake form completed
  □ Risk assessment conducted
  □ Data processing record updated
  □ Semi-annual review

─────────────────────────────────────────────────────────────

TIER 3 — HIGH RISK
  Characteristics:
  • Significant decisions affecting individuals' rights or welfare
  • Sensitive or large-scale personal data processed
  • Automated outputs may be acted on without individual review
  • Outcomes may be difficult to reverse
  Examples: CV screening, loan decisioning, medical triage support,
            performance monitoring, fraud detection
  Controls required:
  □ Full risk assessment completed
  □ DPIA conducted and documented
  □ DPO / Legal sign-off obtained
  □ Human-in-the-loop controls implemented
  □ Bias and fairness evaluation
  □ Quarterly review + incident response plan

─────────────────────────────────────────────────────────────

TIER 4 — CRITICAL RISK
  Characteristics:
  • High-stakes decisions in regulated or safety-critical contexts
  • Biometric, health, financial, or children's data involved
  • Automated decisions at scale with limited human review
  • Severe or irreversible potential harm
  Examples: benefits eligibility determination, criminal risk scoring,
            medical diagnosis, critical infrastructure management
  Controls required:
  □ All Tier 3 controls
  □ Board / executive sign-off
  □ External audit or third-party review
  □ Supervisory authority notification (if required)
  □ Continuous monitoring + real-time alerts
  □ Documented redress and appeal process

─────────────────────────────────────────────────────────────
AUTO-HIGH TRIGGERS
Any of the following automatically elevates a use case to Tier 3+:
  □ Biometric or facial recognition data
  □ Children or vulnerable individuals in scope
  □ Unacceptable-risk AI under EU AI Act
  □ Processing >100,000 individuals' personal data
  □ Law enforcement, immigration, or justice context
  □ Fully automated decisions with legal or equivalent effect
─────────────────────────────────────────────────────────────
Generated free by GovSecure · govsecure.ai
`,

  "ai-approval": () => `AI APPROVAL DECISION RECORD
Generated by GovSecure · ${today()}
─────────────────────────────────────────────────────────────

PURPOSE
Record the formal go / conditional-go / no-go decision, required
approvers, and launch conditions for each AI use case.

─────────────────────────────────────────────────────────────
SECTION 1 — USE CASE REFERENCE
─────────────────────────────────────────────────────────────

Use Case Name:        ________________________________
System / Tool:        ________________________________
Risk Tier:            □ Low   □ Medium   □ High   □ Critical
Date Submitted:       ________________________________
Decision Date:        ________________________________

─────────────────────────────────────────────────────────────
SECTION 2 — REVIEW CHECKLIST
─────────────────────────────────────────────────────────────

Required documentation (tick when complete):
  □ AI Use Case Intake Form
  □ Risk Assessment completed
  □ DPIA completed (Tier 3+)
  □ Data processing record updated
  □ Vendor / procurement due diligence
  □ Security review completed
  □ Bias / fairness evaluation (Tier 3+)
  □ Legal / regulatory review

─────────────────────────────────────────────────────────────
SECTION 3 — FORMAL DECISION
─────────────────────────────────────────────────────────────

Decision (tick one):
  □ GO              — approved to proceed as proposed
  □ CONDITIONAL GO  — approved subject to conditions below
  □ NO-GO           — not approved; reasons below

Conditions / reasons:
  1. ___________________________________________________
  2. ___________________________________________________
  3. ___________________________________________________

─────────────────────────────────────────────────────────────
SECTION 4 — LAUNCH CONDITIONS (for Conditional Go)
─────────────────────────────────────────────────────────────

The following must be satisfied before the system goes live:

CONDITION                        OWNER           DUE DATE
────────────────────────────────────────────────────────────
______________________________   ____________    __________
______________________________   ____________    __________
______________________________   ____________    __________

Conditions verified by:   ________________________________
Verification date:        ________________________________

─────────────────────────────────────────────────────────────
SECTION 5 — REQUIRED APPROVERS
─────────────────────────────────────────────────────────────

ROLE                      NAME                  SIGNATURE     DATE
────────────────────────────────────────────────────────────────────
Business Owner            ________________      __________    ______
DPO / Privacy Lead        ________________      __________    ______
CISO / Security Lead      ________________      __________    ______
Legal Counsel             ________________      __________    ______
Executive Sponsor         ________________      __________    ______

─────────────────────────────────────────────────────────────
SECTION 6 — POST-LAUNCH REVIEW
─────────────────────────────────────────────────────────────

Scheduled review date:    ________________________________
Review owner:             ________________________________
Monitoring plan in place: □ Yes   □ No
Incident contact:         ________________________________

─────────────────────────────────────────────────────────────
Generated free by GovSecure · govsecure.ai
`,
};

function downloadTemplate(id: string) {
  const generator = templateContent[id];
  if (!generator) return;
  const content = generator();
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${id}-govsecure.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Section ──────────────────────────────────────────────────────────────────

export function Playbooks() {
  return (
    <section className="section bg-terminal-dark">
      <div className="max-w-7xl mx-auto">
        {/* Section header */}
        <div className="flex flex-col md:flex-row md:items-end md:justify-between mb-12 gap-4">
          <div>
            <h2 className="section-title">
              AI Governance Life Cycle Templates{" "}
              <span className="text-terminal-muted font-normal">(models &amp; use cases)</span>
            </h2>
            <p className="text-sm font-sans text-terminal-muted mt-2">
              Free to download — no account required.
            </p>
          </div>
          <Link href="/playbooks" className="btn-secondary self-start md:self-auto">
            View All Templates
            <ArrowUpRight className="w-4 h-4" />
          </Link>
        </div>

        {/* Template cards grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {lifecycleTemplates.map((template) => (
            <div key={template.id} className="card group flex flex-col">
              {/* Header with icon + FREE badge */}
              <div className="flex items-start justify-between mb-4">
                <div className="w-10 h-10 flex items-center justify-center border border-terminal-border rounded bg-terminal-gray group-hover:border-terminal-green/50 transition-colors">
                  <BookOpen className="w-5 h-5 text-terminal-green" />
                </div>
                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-mono font-semibold bg-terminal-green/15 text-terminal-green border border-terminal-green/30">
                  FREE
                </span>
              </div>

              {/* Title */}
              <h3 className="font-mono text-lg font-bold text-terminal-text mb-2 group-hover:text-terminal-green transition-colors">
                {template.title}
              </h3>

              {/* Description */}
              <p className="text-terminal-muted font-sans text-sm leading-relaxed flex-grow">
                {template.description}
              </p>

              {/* Download footer */}
              <div className="mt-4 pt-4 border-t border-terminal-border flex items-center justify-between">
                <span className="text-xs font-mono text-terminal-muted">
                  No sign-up needed
                </span>
                <button
                  onClick={() => downloadTemplate(template.id)}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono font-semibold text-terminal-green border border-terminal-green/40 bg-terminal-green/10 hover:bg-terminal-green/20 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
